# Generated by Django 2.1.15 on 2020-06-10 02:32

import colorfield.fields
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('Font_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('homeslider_text1', models.CharField(blank=True, max_length=500, null=True)),
                ('homeslider_text2', models.CharField(blank=True, max_length=500, null=True)),
                ('homeslider_text3', models.CharField(blank=True, max_length=500, null=True)),
                ('homeslider1', models.URLField(blank=True, db_index=True, max_length=128)),
                ('homeslider2', models.URLField(blank=True, db_index=True, max_length=128)),
                ('homeslider3', models.URLField(blank=True, db_index=True, max_length=128)),
                ('homeimage1', models.ImageField(upload_to='logo/')),
                ('homeimage2', models.ImageField(upload_to='logo/')),
                ('homeimage3', models.ImageField(upload_to='logo/')),
                ('validFrom', models.DateTimeField(default=datetime.datetime.now)),
                ('validTo', models.DateTimeField(default=datetime.datetime.now)),
                ('Is_active', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('ip_address', models.CharField(blank=True, max_length=255, verbose_name='Registration IP')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country Name')),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
