# Generated by Django 2.1.15 on 2020-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auditentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditentry',
            name='date_time',
            field=models.DateTimeField(max_length=256, null=True),
        ),
    ]
