# Generated by Django 2.1.15 on 2020-06-11 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auditentry_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_email_change_permission',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
