# Generated by Django 2.1.15 on 2020-06-15 08:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_blockip'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='control_campaigns',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_channel', models.CharField(blank=True, max_length=1000)),
                ('whitelist_channel', models.CharField(max_length=1000)),
                ('keywords', models.CharField(blank=True, max_length=1000)),
                ('ads_status', models.BooleanField(default=0)),
                ('ads_percentage', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='useradmin_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('authentication', models.BooleanField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.control_campaigns')),
            ],
        ),
        migrations.AddField(
            model_name='campaign_report',
            name='campaign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.control_campaigns'),
        ),
    ]
