# Generated by Django 2.1.15 on 2020-06-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200615_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign_report',
            name='cpc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign_report',
            name='cpm',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
