# Generated by Django 2.1.15 on 2020-06-20 08:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adwords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('model_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(default=uuid.uuid4, max_length=225)),
                ('ad_group_id', models.CharField(default=uuid.uuid4, max_length=225)),
                ('created_by', models.CharField(max_length=200)),
                ('campaigns_name', models.CharField(max_length=224)),
                ('bidding_strategy', models.CharField(max_length=224)),
                ('budget_type', models.CharField(max_length=100)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_search_results', models.IntegerField(default=0)),
                ('youtube_videos', models.IntegerField(default=0)),
                ('video_partners', models.IntegerField(default=0)),
                ('languages', models.CharField(max_length=200)),
                ('locations', models.CharField(max_length=200)),
                ('inventory_types', models.CharField(max_length=200)),
                ('ad_group_name', models.CharField(max_length=200)),
                ('demographics', models.CharField(max_length=200)),
                ('audiences', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=1000)),
                ('topics', models.CharField(max_length=1000)),
                ('placements', models.CharField(max_length=1000)),
                ('cpv_bid', models.IntegerField(default=0, null=True)),
                ('url', models.CharField(max_length=1000)),
                ('ads_format', models.CharField(max_length=100)),
                ('approved', models.IntegerField(default=0)),
                ('pause', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign_reports',
            name='link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adwords.campaign'),
        ),
        migrations.DeleteModel(
            name='campaigns',
        ),
    ]
