# Generated by Django 2.1.15 on 2020-06-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords', '0002_auto_20200620_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='update_status',
            field=models.IntegerField(default=0),
        ),
    ]
