# Generated by Django 2.1.15 on 2020-06-20 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adwords', '0003_campaign_update_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='update_status',
            new_name='update_pending',
        ),
    ]
