# Generated by Django 2.1.15 on 2020-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwords', '0004_auto_20200620_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
